
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;



public partial class CfgAction
{
    private readonly System.Collections.Generic.Dictionary<int, RowCfgAction> _dataMap;
    private readonly System.Collections.Generic.List<RowCfgAction> _dataList;
    
    public CfgAction(ByteBuf _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, RowCfgAction>();
        _dataList = new System.Collections.Generic.List<RowCfgAction>();
        
        for(int n = _buf.ReadSize() ; n > 0 ; --n)
        {
            RowCfgAction _v;
            _v = RowCfgAction.DeserializeRowCfgAction(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, RowCfgAction> DataMap => _dataMap;
    public System.Collections.Generic.List<RowCfgAction> DataList => _dataList;

    public RowCfgAction GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public RowCfgAction Get(int key) => _dataMap[key];
    public RowCfgAction this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}



