
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;



public partial class CfgCamera
{
    private readonly System.Collections.Generic.Dictionary<string, RowCfgCamera> _dataMap;
    private readonly System.Collections.Generic.List<RowCfgCamera> _dataList;
    
    public CfgCamera(ByteBuf _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<string, RowCfgCamera>();
        _dataList = new System.Collections.Generic.List<RowCfgCamera>();
        
        for(int n = _buf.ReadSize() ; n > 0 ; --n)
        {
            RowCfgCamera _v;
            _v = RowCfgCamera.DeserializeRowCfgCamera(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<string, RowCfgCamera> DataMap => _dataMap;
    public System.Collections.Generic.List<RowCfgCamera> DataList => _dataList;

    public RowCfgCamera GetOrDefault(string key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public RowCfgCamera Get(string key) => _dataMap[key];
    public RowCfgCamera this[string key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}



