
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;



public partial class CfgCondition
{
    private readonly System.Collections.Generic.Dictionary<int, RowCfgCondition> _dataMap;
    private readonly System.Collections.Generic.List<RowCfgCondition> _dataList;
    
    public CfgCondition(ByteBuf _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, RowCfgCondition>();
        _dataList = new System.Collections.Generic.List<RowCfgCondition>();
        
        for(int n = _buf.ReadSize() ; n > 0 ; --n)
        {
            RowCfgCondition _v;
            _v = RowCfgCondition.DeserializeRowCfgCondition(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, RowCfgCondition> DataMap => _dataMap;
    public System.Collections.Generic.List<RowCfgCondition> DataList => _dataList;

    public RowCfgCondition GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public RowCfgCondition Get(int key) => _dataMap[key];
    public RowCfgCondition this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}



