
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;



public partial class CfgDialogue
{
    private readonly System.Collections.Generic.Dictionary<int, RowCfgDialogue> _dataMap;
    private readonly System.Collections.Generic.List<RowCfgDialogue> _dataList;
    
    public CfgDialogue(ByteBuf _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, RowCfgDialogue>();
        _dataList = new System.Collections.Generic.List<RowCfgDialogue>();
        
        for(int n = _buf.ReadSize() ; n > 0 ; --n)
        {
            RowCfgDialogue _v;
            _v = RowCfgDialogue.DeserializeRowCfgDialogue(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, RowCfgDialogue> DataMap => _dataMap;
    public System.Collections.Generic.List<RowCfgDialogue> DataList => _dataList;

    public RowCfgDialogue GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public RowCfgDialogue Get(int key) => _dataMap[key];
    public RowCfgDialogue this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}



