
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;



public partial class CfgDialogueOption
{
    private readonly System.Collections.Generic.Dictionary<int, RowCfgDialogueOption> _dataMap;
    private readonly System.Collections.Generic.List<RowCfgDialogueOption> _dataList;
    
    public CfgDialogueOption(ByteBuf _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, RowCfgDialogueOption>();
        _dataList = new System.Collections.Generic.List<RowCfgDialogueOption>();
        
        for(int n = _buf.ReadSize() ; n > 0 ; --n)
        {
            RowCfgDialogueOption _v;
            _v = RowCfgDialogueOption.DeserializeRowCfgDialogueOption(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, RowCfgDialogueOption> DataMap => _dataMap;
    public System.Collections.Generic.List<RowCfgDialogueOption> DataList => _dataList;

    public RowCfgDialogueOption GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public RowCfgDialogueOption Get(int key) => _dataMap[key];
    public RowCfgDialogueOption this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}



