
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;



public partial class CfgFont
{
    private readonly System.Collections.Generic.Dictionary<string, RowCfgFont> _dataMap;
    private readonly System.Collections.Generic.List<RowCfgFont> _dataList;
    
    public CfgFont(ByteBuf _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<string, RowCfgFont>();
        _dataList = new System.Collections.Generic.List<RowCfgFont>();
        
        for(int n = _buf.ReadSize() ; n > 0 ; --n)
        {
            RowCfgFont _v;
            _v = RowCfgFont.DeserializeRowCfgFont(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<string, RowCfgFont> DataMap => _dataMap;
    public System.Collections.Generic.List<RowCfgFont> DataList => _dataList;

    public RowCfgFont GetOrDefault(string key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public RowCfgFont Get(string key) => _dataMap[key];
    public RowCfgFont this[string key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}



