
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;



public partial class CfgGlobal
{
    private readonly System.Collections.Generic.Dictionary<string, RowCfgGlobal> _dataMap;
    private readonly System.Collections.Generic.List<RowCfgGlobal> _dataList;
    
    public CfgGlobal(ByteBuf _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<string, RowCfgGlobal>();
        _dataList = new System.Collections.Generic.List<RowCfgGlobal>();
        
        for(int n = _buf.ReadSize() ; n > 0 ; --n)
        {
            RowCfgGlobal _v;
            _v = RowCfgGlobal.DeserializeRowCfgGlobal(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<string, RowCfgGlobal> DataMap => _dataMap;
    public System.Collections.Generic.List<RowCfgGlobal> DataList => _dataList;

    public RowCfgGlobal GetOrDefault(string key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public RowCfgGlobal Get(string key) => _dataMap[key];
    public RowCfgGlobal this[string key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}



