
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;



public partial class CfgHUD
{
    private readonly System.Collections.Generic.Dictionary<string, RowCfgHUD> _dataMap;
    private readonly System.Collections.Generic.List<RowCfgHUD> _dataList;
    
    public CfgHUD(ByteBuf _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<string, RowCfgHUD>();
        _dataList = new System.Collections.Generic.List<RowCfgHUD>();
        
        for(int n = _buf.ReadSize() ; n > 0 ; --n)
        {
            RowCfgHUD _v;
            _v = RowCfgHUD.DeserializeRowCfgHUD(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<string, RowCfgHUD> DataMap => _dataMap;
    public System.Collections.Generic.List<RowCfgHUD> DataList => _dataList;

    public RowCfgHUD GetOrDefault(string key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public RowCfgHUD Get(string key) => _dataMap[key];
    public RowCfgHUD this[string key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}



