
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;



public partial class CfgLocalization
{
    private readonly System.Collections.Generic.Dictionary<int, RowCfgLocalization> _dataMap;
    private readonly System.Collections.Generic.List<RowCfgLocalization> _dataList;
    
    public CfgLocalization(ByteBuf _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, RowCfgLocalization>();
        _dataList = new System.Collections.Generic.List<RowCfgLocalization>();
        
        for(int n = _buf.ReadSize() ; n > 0 ; --n)
        {
            RowCfgLocalization _v;
            _v = RowCfgLocalization.DeserializeRowCfgLocalization(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, RowCfgLocalization> DataMap => _dataMap;
    public System.Collections.Generic.List<RowCfgLocalization> DataList => _dataList;

    public RowCfgLocalization GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public RowCfgLocalization Get(int key) => _dataMap[key];
    public RowCfgLocalization this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}



