
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;



public partial class CfgLocalizationImage
{
    private readonly System.Collections.Generic.Dictionary<int, RowCfgLocalizationImage> _dataMap;
    private readonly System.Collections.Generic.List<RowCfgLocalizationImage> _dataList;
    
    public CfgLocalizationImage(ByteBuf _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, RowCfgLocalizationImage>();
        _dataList = new System.Collections.Generic.List<RowCfgLocalizationImage>();
        
        for(int n = _buf.ReadSize() ; n > 0 ; --n)
        {
            RowCfgLocalizationImage _v;
            _v = RowCfgLocalizationImage.DeserializeRowCfgLocalizationImage(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, RowCfgLocalizationImage> DataMap => _dataMap;
    public System.Collections.Generic.List<RowCfgLocalizationImage> DataList => _dataList;

    public RowCfgLocalizationImage GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public RowCfgLocalizationImage Get(int key) => _dataMap[key];
    public RowCfgLocalizationImage this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}



