
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;



public partial class CfgPrefab
{
    private readonly System.Collections.Generic.Dictionary<string, RowCfgPrefab> _dataMap;
    private readonly System.Collections.Generic.List<RowCfgPrefab> _dataList;
    
    public CfgPrefab(ByteBuf _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<string, RowCfgPrefab>();
        _dataList = new System.Collections.Generic.List<RowCfgPrefab>();
        
        for(int n = _buf.ReadSize() ; n > 0 ; --n)
        {
            RowCfgPrefab _v;
            _v = RowCfgPrefab.DeserializeRowCfgPrefab(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<string, RowCfgPrefab> DataMap => _dataMap;
    public System.Collections.Generic.List<RowCfgPrefab> DataList => _dataList;

    public RowCfgPrefab GetOrDefault(string key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public RowCfgPrefab Get(string key) => _dataMap[key];
    public RowCfgPrefab this[string key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}



