
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;



public partial class CfgSFX
{
    private readonly System.Collections.Generic.Dictionary<string, RowCfgSFX> _dataMap;
    private readonly System.Collections.Generic.List<RowCfgSFX> _dataList;
    
    public CfgSFX(ByteBuf _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<string, RowCfgSFX>();
        _dataList = new System.Collections.Generic.List<RowCfgSFX>();
        
        for(int n = _buf.ReadSize() ; n > 0 ; --n)
        {
            RowCfgSFX _v;
            _v = RowCfgSFX.DeserializeRowCfgSFX(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<string, RowCfgSFX> DataMap => _dataMap;
    public System.Collections.Generic.List<RowCfgSFX> DataList => _dataList;

    public RowCfgSFX GetOrDefault(string key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public RowCfgSFX Get(string key) => _dataMap[key];
    public RowCfgSFX this[string key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}



