
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



 
    public enum DefSFXType
    {
        /// <summary>
        /// 音效
        /// </summary>
        Se = 0,
        /// <summary>
        /// 语音
        /// </summary>
        Voice = 1,
    }

 

