
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;



public sealed partial class RowCfgAction : Luban.BeanBase
{
    public RowCfgAction(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        {int n0 = System.Math.Min(_buf.ReadSize(), _buf.Size);AtomActionList = new System.Collections.Generic.List<int>(n0);for(var i0 = 0 ; i0 < n0 ; i0++) { int _e0;  _e0 = _buf.ReadInt(); AtomActionList.Add(_e0);}}
        {int __n0 = System.Math.Min(_buf.ReadSize(), _buf.Size);ParamList = new string[__n0][];for(var __index0 = 0 ; __index0 < __n0 ; __index0++) { string[] __e0;{int __n1 = System.Math.Min(_buf.ReadSize(), _buf.Size);__e0 = new string[__n1];for(var __index1 = 0 ; __index1 < __n1 ; __index1++) { string __e1;__e1 = _buf.ReadString(); __e0[__index1] = __e1;}} ParamList[__index0] = __e0;}}
    }

    public static RowCfgAction DeserializeRowCfgAction(ByteBuf _buf)
    {
        return new RowCfgAction(_buf);
    }

    /// <summary>
    /// id
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 原子事件列表
    /// </summary>
    public readonly System.Collections.Generic.List<int> AtomActionList;
    /// <summary>
    /// 原子事件1参数
    /// </summary>
    public readonly string[][] ParamList;
   
    public const int __ID__ = -2096414944;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        
        
        
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "atomActionList:" + Luban.StringUtil.CollectionToString(AtomActionList) + ","
        + "paramList:" + Luban.StringUtil.CollectionToString(ParamList) + ","
        + "}";
    }
}


