
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;



public sealed partial class RowCfgBgm : Luban.BeanBase
{
    public RowCfgBgm(ByteBuf _buf) 
    {
        Id = _buf.ReadString();
        AudioClipPath = _buf.ReadString();
    }

    public static RowCfgBgm DeserializeRowCfgBgm(ByteBuf _buf)
    {
        return new RowCfgBgm(_buf);
    }

    /// <summary>
    /// bgm名
    /// </summary>
    public readonly string Id;
    /// <summary>
    /// 资源路径
    /// </summary>
    public readonly string AudioClipPath;
   
    public const int __ID__ = -1749715938;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        
        
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "audioClipPath:" + AudioClipPath + ","
        + "}";
    }
}


