
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;



public sealed partial class RowCfgFont : Luban.BeanBase
{
    public RowCfgFont(ByteBuf _buf) 
    {
        Id = _buf.ReadString();
        FontPath = _buf.ReadString();
        SdfFontPath = _buf.ReadString();
    }

    public static RowCfgFont DeserializeRowCfgFont(ByteBuf _buf)
    {
        return new RowCfgFont(_buf);
    }

    /// <summary>
    /// 字体id
    /// </summary>
    public readonly string Id;
    /// <summary>
    /// 字体资源路径
    /// </summary>
    public readonly string FontPath;
    /// <summary>
    /// TMP字体资源路径
    /// </summary>
    public readonly string SdfFontPath;
   
    public const int __ID__ = 1593507769;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        
        
        
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "FontPath:" + FontPath + ","
        + "SdfFontPath:" + SdfFontPath + ","
        + "}";
    }
}


