
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;



public sealed partial class RowCfgDialogue : Luban.BeanBase
{
    public RowCfgDialogue(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        NextId = _buf.ReadInt();
        TextId = _buf.ReadInt();
        {int n0 = System.Math.Min(_buf.ReadSize(), _buf.Size);OptionIds = new System.Collections.Generic.List<int>(n0);for(var i0 = 0 ; i0 < n0 ; i0++) { int _e0;  _e0 = _buf.ReadInt(); OptionIds.Add(_e0);}}
        {int n0 = System.Math.Min(_buf.ReadSize(), _buf.Size);ActionIds = new System.Collections.Generic.List<int>(n0);for(var i0 = 0 ; i0 < n0 ; i0++) { int _e0;  _e0 = _buf.ReadInt(); ActionIds.Add(_e0);}}
        {int n0 = System.Math.Min(_buf.ReadSize(), _buf.Size);AtomActionIds = new System.Collections.Generic.List<int>(n0);for(var i0 = 0 ; i0 < n0 ; i0++) { int _e0;  _e0 = _buf.ReadInt(); AtomActionIds.Add(_e0);}}
        {int __n0 = System.Math.Min(_buf.ReadSize(), _buf.Size);AtomActionParamList = new string[__n0][];for(var __index0 = 0 ; __index0 < __n0 ; __index0++) { string[] __e0;{int __n1 = System.Math.Min(_buf.ReadSize(), _buf.Size);__e0 = new string[__n1];for(var __index1 = 0 ; __index1 < __n1 ; __index1++) { string __e1;__e1 = _buf.ReadString(); __e0[__index1] = __e1;}} AtomActionParamList[__index0] = __e0;}}
    }

    public static RowCfgDialogue DeserializeRowCfgDialogue(ByteBuf _buf)
    {
        return new RowCfgDialogue(_buf);
    }

    /// <summary>
    /// id
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 跳转剧情id
    /// </summary>
    public readonly int NextId;
    /// <summary>
    /// 文本id
    /// </summary>
    public readonly int TextId;
    /// <summary>
    /// 剧情选项列表
    /// </summary>
    public readonly System.Collections.Generic.List<int> OptionIds;
    /// <summary>
    /// 事件id列表
    /// </summary>
    public readonly System.Collections.Generic.List<int> ActionIds;
    /// <summary>
    /// 原子事件id列表
    /// </summary>
    public readonly System.Collections.Generic.List<int> AtomActionIds;
    /// <summary>
    /// 原子事件1参数
    /// </summary>
    public readonly string[][] AtomActionParamList;
   
    public const int __ID__ = 1107232834;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        
        
        
        
        
        
        
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "nextId:" + NextId + ","
        + "textId:" + TextId + ","
        + "optionIds:" + Luban.StringUtil.CollectionToString(OptionIds) + ","
        + "actionIds:" + Luban.StringUtil.CollectionToString(ActionIds) + ","
        + "atomActionIds:" + Luban.StringUtil.CollectionToString(AtomActionIds) + ","
        + "atomActionParamList:" + Luban.StringUtil.CollectionToString(AtomActionParamList) + ","
        + "}";
    }
}


