
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;



public sealed partial class RowCfgLocalization : Luban.BeanBase
{
    public RowCfgLocalization(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        ZhCN = _buf.ReadString();
        En = _buf.ReadString();
        Jp = _buf.ReadString();
    }

    public static RowCfgLocalization DeserializeRowCfgLocalization(ByteBuf _buf)
    {
        return new RowCfgLocalization(_buf);
    }

    /// <summary>
    /// 文本id
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 简体中文
    /// </summary>
    public readonly string ZhCN;
    /// <summary>
    /// 英文
    /// </summary>
    public readonly string En;
    /// <summary>
    /// 日文
    /// </summary>
    public readonly string Jp;
   
    public const int __ID__ = 504868867;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        
        
        
        
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "zhCN:" + ZhCN + ","
        + "en:" + En + ","
        + "jp:" + Jp + ","
        + "}";
    }
}


