
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;



public sealed partial class RowCfgSprite : Luban.BeanBase
{
    public RowCfgSprite(ByteBuf _buf) 
    {
        Id = _buf.ReadString();
        SpritePath = _buf.ReadString();
    }

    public static RowCfgSprite DeserializeRowCfgSprite(ByteBuf _buf)
    {
        return new RowCfgSprite(_buf);
    }

    /// <summary>
    /// sprite名
    /// </summary>
    public readonly string Id;
    /// <summary>
    /// 预设路径
    /// </summary>
    public readonly string SpritePath;
   
    public const int __ID__ = -1569143889;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        
        
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "spritePath:" + SpritePath + ","
        + "}";
    }
}


