
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;



public sealed partial class RowCfgUI : Luban.BeanBase
{
    public RowCfgUI(ByteBuf _buf) 
    {
        Id = _buf.ReadString();
        UiPath = _buf.ReadString();
        Layer = _buf.ReadString();
        SortOrder = _buf.ReadInt();
    }

    public static RowCfgUI DeserializeRowCfgUI(ByteBuf _buf)
    {
        return new RowCfgUI(_buf);
    }

    /// <summary>
    /// UI名
    /// </summary>
    public readonly string Id;
    /// <summary>
    /// 资源路径
    /// </summary>
    public readonly string UiPath;
    /// <summary>
    /// 所属层级
    /// </summary>
    public readonly string Layer;
    /// <summary>
    /// 图层层级
    /// </summary>
    public readonly int SortOrder;
   
    public const int __ID__ = 82105438;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        
        
        
        
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "uiPath:" + UiPath + ","
        + "layer:" + Layer + ","
        + "sortOrder:" + SortOrder + ","
        + "}";
    }
}


