
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;



public sealed partial class RowCfgDialogueOption : Luban.BeanBase
{
    public RowCfgDialogueOption(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        NextId = _buf.ReadInt();
        TextId = _buf.ReadInt();
        CondId = _buf.ReadInt();
    }

    public static RowCfgDialogueOption DeserializeRowCfgDialogueOption(ByteBuf _buf)
    {
        return new RowCfgDialogueOption(_buf);
    }

    /// <summary>
    /// 选项id
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 跳转剧情id
    /// </summary>
    public readonly int NextId;
    /// <summary>
    /// 文本id
    /// </summary>
    public readonly int TextId;
    /// <summary>
    /// 显示条件id
    /// </summary>
    public readonly int CondId;
   
    public const int __ID__ = -383532201;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        
        
        
        
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "nextId:" + NextId + ","
        + "textId:" + TextId + ","
        + "condId:" + CondId + ","
        + "}";
    }
}


