
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;



public sealed partial class RowCfgHUD : Luban.BeanBase
{
    public RowCfgHUD(ByteBuf _buf) 
    {
        Id = _buf.ReadString();
        UiPath = _buf.ReadString();
    }

    public static RowCfgHUD DeserializeRowCfgHUD(ByteBuf _buf)
    {
        return new RowCfgHUD(_buf);
    }

    /// <summary>
    /// UI名
    /// </summary>
    public readonly string Id;
    /// <summary>
    /// 预设路径
    /// </summary>
    public readonly string UiPath;
   
    public const int __ID__ = -1749710771;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        
        
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "uiPath:" + UiPath + ","
        + "}";
    }
}


